Allow headers to be omitted from response
Kentico/kontent-delivery-sdk-ruby pull request #51
Opened 2020-12-04 16:10 UTC by alypeng

### Motivation

`ResponseBase` is initialised with only two arguments in a few places (e.g. https://github.com/Kentico/kontent-delivery-sdk-ruby/blob/5d3f29d0f870f78f8298285c07bc5fcfd56e9fe4/lib/delivery/client/request_manager.rb#L57) when it currently requires at least three arguments. This causes the error handling logic to raise an `ArgumentError` instead of returning a `ResponseBase` as expected.

This can be reproduced with the following code

```ruby
dc = Kentico::Kontent::Delivery::DeliveryClient.new(project_id: '123')
dc.item('123').execute
```

which results in

```
ArgumentError (wrong number of arguments (given 2, expected 3..4))
```

2020-12-04 18:52 UTC, kentico-ericd requested changes
Hello @alypeng! Thanks for the PR, that does fix it 👍 

Can you please bump the [version](https://github.com/Kentico/kontent-delivery-sdk-ruby/blob/master/lib/delivery/version.rb) to 2.0.17 and tag the commit with "v2.0.17"

2020-12-08 16:35 UTC, alypeng commented
@kentico-ericd Done 👍

2020-12-08 18:28 UTC, kentico-ericd approved these changes

2020-12-08 18:28 UTC, merged

2020-12-08 19:27 UTC, kentico-ericd commented
Thanks for the help @alypeng 😃